// LDPCdecoder_ldpc_0_decoder.v

// This file was auto-generated from altera_ldpc_dec_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module LDPCdecoder_ldpc_0_decoder #(
		parameter CHANNEL         = 1,
		parameter BITSPERSYMBOL   = 2,
		parameter N               = 1200,
		parameter NBCHECKGROUP    = 12,
		parameter NBVARGROUP      = 44,
		parameter SOFTBITS        = 3,
		parameter PAR             = 2,
		parameter NB_ITE          = 10,
		parameter TRANSMIT_PARITY = 0,
		parameter ATTENUATION     = 1,
		parameter S               = 4,
		parameter EXTRALATENCY    = 0
	) (
		input  wire       clk_clk,           // clk.clk
		input  wire       rst_reset_n,       // rst.reset_n
		input  wire       in_startofpacket,  //  in.startofpacket
		input  wire       in_endofpacket,    //    .endofpacket
		input  wire       in_valid,          //    .valid
		output wire       in_ready,          //    .ready
		input  wire [5:0] in_cw_in_data,     //    .cw_in_data
		output wire       out_startofpacket, // out.startofpacket
		output wire       out_endofpacket,   //    .endofpacket
		output wire       out_valid,         //    .valid
		input  wire       out_ready,         //    .ready
		output wire [1:0] out_data           //    .data
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (CHANNEL != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					channel_check ( .error(1'b1) );
		end
		if (BITSPERSYMBOL != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bitspersymbol_check ( .error(1'b1) );
		end
		if (N != 1200)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					n_check ( .error(1'b1) );
		end
		if (NBCHECKGROUP != 12)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					nbcheckgroup_check ( .error(1'b1) );
		end
		if (NBVARGROUP != 44)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					nbvargroup_check ( .error(1'b1) );
		end
		if (SOFTBITS != 3)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					softbits_check ( .error(1'b1) );
		end
		if (PAR != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					par_check ( .error(1'b1) );
		end
		if (NB_ITE != 10)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					nb_ite_check ( .error(1'b1) );
		end
		if (TRANSMIT_PARITY != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					transmit_parity_check ( .error(1'b1) );
		end
		if (ATTENUATION != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					attenuation_check ( .error(1'b1) );
		end
		if (S != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s_check ( .error(1'b1) );
		end
		if (EXTRALATENCY != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					extralatency_check ( .error(1'b1) );
		end
	endgenerate

	altera_ldpc_wimedia_msa #(
		.CHANNEL         (1),
		.BITSPERSYMBOL   (2),
		.N               (1200),
		.NBCHECKGROUP    (8),
		.NBVARGROUP      (40),
		.SOFTBITS        (3),
		.PAR             (2),
		.NB_ITE          (10),
		.TRANSMIT_PARITY (0),
		.ATTENUATION     (1),
		.S               (4),
		.EXTRALATENCY    (0)
	) dec_msa (
		.clk          (clk_clk),           //    clk.clk
		.rst          (~rst_reset_n),      //    rst.reset
		.cw_in_sop    (in_startofpacket),  //  cw_in.startofpacket
		.cw_in_eop    (in_endofpacket),    //       .endofpacket
		.cw_in_valid  (in_valid),          //       .valid
		.cw_in_ready  (in_ready),          //       .ready
		.cw_in_data   (in_cw_in_data),     //       .cw_in_data
		.cw_out_sop   (out_startofpacket), // cw_out.startofpacket
		.cw_out_eop   (out_endofpacket),   //       .endofpacket
		.cw_out_valid (out_valid),         //       .valid
		.cw_out_ready (out_ready),         //       .ready
		.cw_out_data  (out_data)           //       .data
	);

endmodule
